# Generated by Django 3.2 on 2022-11-20 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.member'),
        ),
        migrations.AlterField(
            model_name='post',
            name='delete_at',
            field=models.DateTimeField(null=True),
        ),
    ]
